[AURON #1597] Fix java.lang.NoClassDefFoundError: io/netty/buffer/Unpooled when running with shaded-spark  (#1598)
* introduce netty

* cleanup comments

* address comments

---------

Co-authored-by: sarangat_LinkedIn <sarangath@linkedin.com>